#! /bin/bash

# Prelude
d=`pwd`
cd ~/code/nomad

for file in `ls templates/pages`
do
sed "
1a \
	<!-- DO NOT EDIT THIS FILE -->
/~BODY~/ {
	r templates/pages/$file
	d
}" templates/wrapper.html > static/$file
done

# Postlude
cd $d
