#! /bin/bash

# Prelude
if [ $CODE_DIR = '' ]
then 
	echo 'please export CODE_DIR' >&2
	exit 1
fi
d=`pwd`
cd $CODE_DIR/nomad

for file in `ls templates/pages`
do
sed "
1a \
	<!-- DO NOT EDIT THIS FILE -->
/~BODY~/ {
	r templates/pages/$file
	d
}" templates/wrapper.html > static/$file
done

# Postlude
cd $d
