#! /bin/bash

# Prelude
if [ "$CODE_DIR" = '' ]
then 
	echo 'please export CODE_DIR' >&2
	exit 1
fi
if [ "$NOMAD_ROOT" = '' ]
then 
	echo 'please export NOMAD_ROOT' >&2
	exit 1
fi

dir="$CODE_DIR/nomad"


node $dir/scripts/generateSignIn.mjs > $dir/templates/local/sign-in.html

for file in `ls $dir/templates/local`
do
sed "
1a \
	<!-- DO NOT EDIT THIS FILE -->
/~BODY~/ {
	r $dir/templates/local/$file
	d
}" $dir/templates/local_wrapper.html | sed "s#~ROOT#$NOMAD_ROOT#" > $dir/local/$file
done

sed "s#~ROOT#$NOMAD_ROOT#" < $dir/templates/roboto.css > $dir/static/css/roboto.css
