#! /bin/bash

# Prelude
echo "starting at: `date`" >> /home/kswnin/generate.log
if [ "$CODE_DIR" = '' ]
then 
	echo 'please export CODE_DIR' >&2
	exit 1
fi
dir="$CODE_DIR/nomad"
echo "Dir: $dir" >> /home/kswnin/generate.log

curl https://calendar.google.com/calendar/ical/d4d0773546ae6d7e69b104a3f0a6e612ee49bf31fcd87463de373f9819be336c%40group.calendar.google.com/private-1250974c781dffb16a03c7b44773371d/basic.ics \
	| node $dir/scripts/calendarToHTML.mjs > $dir/templates/pages/schedule.html

for file in `ls $dir/templates/pages`
do
sed "
1a \
	<!-- DO NOT EDIT THIS FILE -->
/~BODY~/ {
	r $dir/templates/pages/$file
	d
}" $dir/templates/wrapper.html > $dir/static/$file
done

echo "ending at: `date`" >> /home/kswnin/generate.log
